/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        h1: ['Inter'],
        h2: ['Inter'],
        h3: ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        caption: ['Inter'],
      },
      fontSize: {
        h1: ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        caption: ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      colors: {
        primary: '#5343b9',
        'primary-container': '#6c5dd3',
        'primary-fixed': '#e5deff',
        'primary-fixed-dim': '#c7bfff',
        'on-primary': '#ffffff',
        'on-primary-container': '#f5f0ff',
        'on-primary-fixed': '#180065',
        'on-primary-fixed-variant': '#4331a8',
        'inverse-primary': '#c7bfff',
        secondary: '#5c5d6c',
        'secondary-container': '#dedef0',
        'secondary-fixed': '#e1e1f3',
        'secondary-fixed-dim': '#c5c5d7',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#606271',
        'on-secondary-fixed': '#191b27',
        'on-secondary-fixed-variant': '#444654',
        tertiary: '#52575c',
        'tertiary-container': '#6a6f75',
        'tertiary-fixed': '#dfe3ea',
        'tertiary-fixed-dim': '#c2c7ce',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#eff3fa',
        'on-tertiary-fixed': '#171c21',
        'on-tertiary-fixed-variant': '#42474d',
        surface: '#fcf8ff',
        'surface-dim': '#ddd8e3',
        'surface-bright': '#fcf8ff',
        'surface-container': '#f1ecf7',
        'surface-container-low': '#f6f2fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ebe6f1',
        'surface-container-highest': '#e5e1eb',
        'surface-variant': '#e5e1eb',
        'surface-tint': '#5b4cc1',
        background: '#fcf8ff',
        'on-background': '#1c1b22',
        'on-surface': '#1c1b22',
        'on-surface-variant': '#474553',
        'inverse-surface': '#312f37',
        'inverse-on-surface': '#f4eff9',
        outline: '#787584',
        'outline-variant': '#c9c4d5',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'sidebar-width': '240px',
        'container-padding': '32px',
      },
    },
  },
  plugins: [],
};
